"""ARCH0 — the baseline mechanism guards itself.

These tests prove the committed baselines are (a) DETERMINISTIC and CURRENT — a
fresh regeneration reproduces them byte-for-byte, so the committed state really
is today's model truth — and (b) LOAD-BEARING — a tampered baseline is caught
loudly and named. Plus the annotation discipline: every pinned site-divergence
finding carries a real justification note (no ``TODO-JUSTIFY`` placeholder can be
committed).
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import pytest

import baseline_lib as bl

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))
import regen_baselines as regen  # noqa: E402

COMMITTED = sorted(p.name for p in bl.BASELINE_DIR.glob("*.json"))


def _stale_vs(source_dir: Path) -> set[str]:
    """Regenerate every surface into a temp dir (notes sourced from
    ``source_dir``) and return the filenames whose regenerated bytes differ from
    ``source_dir`` — i.e. the stale or tampered surfaces."""
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        regen.regenerate(out, source_dir=source_dir)
        stale = set()
        for f in out.glob("*.json"):
            src = source_dir / f.name
            if not src.exists() or src.read_text() != f.read_text():
                stale.add(f.name)
        return stale


def test_all_surfaces_are_committed():
    expected = sorted(f"{n}.json" for n in
                      list(bl.SIMPLE_SURFACES) + ["site_divergence"])
    assert COMMITTED == expected


def test_regen_round_trip_reproduces_committed_baselines():
    """Regenerating reproduces the committed baselines byte-for-byte. Proves
    determinism AND that the committed state is current (no baseline drifted from
    the live model). Notes are read from the committed dir, so the annotated
    surface round-trips too."""
    stale = _stale_vs(bl.BASELINE_DIR)
    assert stale == set(), (
        f"STALE baselines {sorted(stale)} — the live model diverged from the "
        f"committed baseline; {bl.REGEN_HINT}")


# Two representative surfaces — a plain computed one and the annotated one (the
# note-merge path) — cover both regeneration code paths. The round-trip test
# above already guards ALL six against drift; these prove a hand-edit is caught
# and named. Kept to two so the heavy model builds don't multiply under xdist.
@pytest.mark.parametrize("name", ["detail_counts.json", "site_divergence.json"])
def test_tampered_baseline_is_caught_and_named(name, tmp_path):
    """Hand-edit a copy of a baseline and regeneration catches it, naming the
    surface — a hand-edit can never masquerade as truth."""
    scratch = tmp_path / "baselines"
    scratch.mkdir()
    for f in bl.BASELINE_DIR.glob("*.json"):
        (scratch / f.name).write_text(f.read_text())
    data = json.loads((scratch / name).read_text())
    data["_tampered"] = "hand-edit that must be caught"
    (scratch / name).write_text(bl.dumps(data))

    stale = _stale_vs(scratch)
    assert name in stale, f"tamper of {name} went undetected"


def test_missing_baseline_teaches_the_regen_command(tmp_path, monkeypatch):
    monkeypatch.setattr(bl, "BASELINE_DIR", tmp_path)  # empty dir
    with pytest.raises(AssertionError) as e:
        bl.load_baseline("detail_counts")
    assert "regen_baselines" in str(e.value)


def test_every_pinned_finding_carries_a_real_note():
    """The annotation channel is enforced: every pinned site-divergence finding
    has a non-empty justification and none is the regen placeholder — an
    un-annotated finding cannot be committed. STRUCT task #19 resolved the last
    pins BY DESIGN, so the set is currently EMPTY (the site validates clean); the
    guard holds vacuously today and re-arms the moment any finding is pinned."""
    findings = bl.load_baseline("site_divergence")["findings"]
    for f in findings:
        note = f.get("note", "")
        assert note and note != regen.TODO_NOTE, (
            f"pinned finding {f['check']}/{f['subject']} needs a justification note")


def test_regen_check_mode_reports_current():
    """The CI ``--check`` mode returns 0 (no writes) when baselines are current."""
    assert regen.main(["--check"]) == 0
