"""Precedent-first product-design selection and lifecycle governance."""

from .loader import load_design_review_file, load_design_review_text
from .fingerprint import (
    model_fingerprint,
    selection_fingerprint,
    selection_payload,
)
from .schema import (
    APPLICATION_STATES,
    ASSESSMENTS,
    CRITERIA,
    SCHEMA_ID,
    SIGNATURE_FIELDS,
    SOURCE_KINDS,
    Approval,
    ArchitectureSignature,
    ComparisonCell,
    Concept,
    ConceptFeature,
    Constraint,
    Decision,
    DeliveryConfirmation,
    DesignBrief,
    DesignReviewDoc,
    DesignReviewSchemaError,
    Deviation,
    NoveltyException,
    PartPurpose,
    Precedent,
    Requirement,
)
from .validation import (
    DesignReviewFinding,
    DesignReviewResult,
    DesignReviewValidationError,
    validate_design_review,
)

__all__ = [
    "APPLICATION_STATES",
    "ASSESSMENTS",
    "CRITERIA",
    "SCHEMA_ID",
    "SIGNATURE_FIELDS",
    "SOURCE_KINDS",
    "Approval",
    "ArchitectureSignature",
    "ComparisonCell",
    "Concept",
    "ConceptFeature",
    "Constraint",
    "Decision",
    "DeliveryConfirmation",
    "DesignBrief",
    "DesignReviewDoc",
    "DesignReviewSchemaError",
    "Deviation",
    "NoveltyException",
    "PartPurpose",
    "Precedent",
    "Requirement",
    "DesignReviewFinding",
    "DesignReviewResult",
    "DesignReviewValidationError",
    "load_design_review_file",
    "load_design_review_text",
    "model_fingerprint",
    "selection_fingerprint",
    "selection_payload",
    "validate_design_review",
]
